import { AppError } from '../middlewares/errorHandler.js';

export const RFQ_STATUSES = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  BROADCASTED: 'BROADCASTED',
  OPEN: 'OPEN',
  NEGOTIATING: 'NEGOTIATING',
  OFFERED: 'OFFERED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED',
  CANCELED: 'CANCELED',
  COMPLETED: 'COMPLETED'
};

const TRANSITIONS = {
  [RFQ_STATUSES.DRAFT]: [RFQ_STATUSES.PENDING, RFQ_STATUSES.CANCELED],
  [RFQ_STATUSES.PENDING]: [RFQ_STATUSES.APPROVED, RFQ_STATUSES.REJECTED, RFQ_STATUSES.CANCELED],
  [RFQ_STATUSES.APPROVED]: [RFQ_STATUSES.BROADCASTED, RFQ_STATUSES.CANCELED],
  [RFQ_STATUSES.BROADCASTED]: [RFQ_STATUSES.OPEN, RFQ_STATUSES.EXPIRED, RFQ_STATUSES.CANCELED],
  [RFQ_STATUSES.OPEN]: [RFQ_STATUSES.NEGOTIATING, RFQ_STATUSES.OFFERED, RFQ_STATUSES.ACCEPTED, RFQ_STATUSES.EXPIRED, RFQ_STATUSES.CANCELED],
  [RFQ_STATUSES.NEGOTIATING]: [RFQ_STATUSES.OFFERED, RFQ_STATUSES.ACCEPTED, RFQ_STATUSES.EXPIRED, RFQ_STATUSES.CANCELED],
  [RFQ_STATUSES.OFFERED]: [RFQ_STATUSES.ACCEPTED, RFQ_STATUSES.REJECTED, RFQ_STATUSES.EXPIRED, RFQ_STATUSES.CANCELED],
  [RFQ_STATUSES.ACCEPTED]: [RFQ_STATUSES.COMPLETED, RFQ_STATUSES.CANCELED],
  [RFQ_STATUSES.REJECTED]: [RFQ_STATUSES.NEGOTIATING, RFQ_STATUSES.CANCELED], // Vendor might counter-offer
  [RFQ_STATUSES.EXPIRED]: [], // Terminal state
  [RFQ_STATUSES.CANCELED]: [], // Terminal state
  [RFQ_STATUSES.COMPLETED]: []  // Terminal state
};

/**
 * Validates if the RFQ status can transition from oldStatus to newStatus.
 * Throws AppError if invalid.
 */
export const validateTransition = (oldStatus, newStatus) => {
  if (!oldStatus || !newStatus) return false;
  
  const allowedTransitions = TRANSITIONS[oldStatus] || [];
  if (!allowedTransitions.includes(newStatus)) {
    throw new AppError(`Invalid status transition from ${oldStatus} to ${newStatus}.`, 400);
  }
  return true;
};
